# Generated by Django 2.1.4 on 2020-08-03 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, default='', max_length=200, verbose_name='Path or URL of the icon')),
            ],
        ),
        migrations.CreateModel(
            name='IssueRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default_relation', models.BooleanField()),
                ('child_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='api.Issue')),
                ('parent_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='api.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('order', models.IntegerField(blank=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Issue')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Platform')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='platform',
            name='issues',
            field=models.ManyToManyField(related_name='_platform_issues_+', through='api.PlatformIssue', to='api.Issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='children',
            field=models.ManyToManyField(related_name='parents', through='api.IssueRelationship', through_fields=('parent_issue', 'child_issue'), to='api.Issue'),
        ),
        migrations.AlterUniqueTogether(
            name='platformissue',
            unique_together={('platform', 'issue', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='issuerelationship',
            unique_together={('parent_issue', 'child_issue')},
        ),
    ]
