# Generated by Django 2.1.4 on 2020-08-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200803_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuerelationship',
            old_name='is_default_relation',
            new_name='is_default_parent',
        ),
    ]
