# Generated by Django 2.1.4 on 2020-08-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200803_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerelationship',
            name='order',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='platformissue',
            unique_together={('platform', 'issue'), ('platform', 'order')},
        ),
    ]
