# Generated by Django 2.1.4 on 2020-08-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200803_0049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuerelationship',
            unique_together={('parent_issue', 'order'), ('parent_issue', 'child_issue')},
        ),
    ]
