# Generated by Django 3.0.8 on 2020-08-03 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assign_issue_roots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='root',
            new_name='default_root',
        ),
    ]
