# Generated by Django 3.0.8 on 2020-08-03 04:47

import backend.api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200803_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformissue',
            name='lineage',
            field=backend.api.models.IssueLineageField(null=True),
        ),
    ]
